### ISSUE TITLE
Mixing CRO/ENG variable names

### ISSUE THREAD

**Issue by jspajic** [ffalak/dba_binlog_cleanup#1]
https://github.com/ffalak/dba_binlog_cleanup/blob/4edcc82f1ebff8327de1d72f937535df80e5d947/purgebinlogs.sh#L7

Hey Franjo, 
can you please rename your variable `sati` to something else?
It's really bad practice mixing two languages(or even using anything else beside English).
Imagine someone without Croatian knowledge browsing your repo and seeing this.

Sincerely, 
Jozo <3

**Comment by ffalak** [comment]
Hey Yozo;

Thank you for your input, I will change it to English, as this was my first script I wan't thinking much about languages and anyone else looking at this, so I understand my error.
In my future scripts I will definitely use only one language (English) to avoid any possible confusions.

Breast regards, 
Franjo
